pipeline { 
    agent any
    stages {
        stage('Build') {
            agent {
               docker {
                  image 'maven:3-alpine'
                   args '-v $HOME/.m2:/root/.m2'
                   reuseNode true
                }
           }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Push') {
           agent none
    		steps {
    		  script {
    		        docker.withRegistry('https://reg.evercenter.cn', 'dockerHarbor'){
    				docker.build('config-service:${BUILD_ID}', '-f config-service/src/main/docker/Dockerfile ./config-service').push()
    				docker.build('discovery-service:${BUILD_ID}', '-f discovery-service/src/main/docker/Dockerfile ./discovery-service').push()
    			}
    		  }
    		}
        }
        stage('Deploy') {
            agent none
    		steps {
    		  script {
    		      sh 'docker-compose -f /opt/seacloud_docker/docker/docker-compose.yml up -d'
    		  }
    		}
        }
        
        
        
    }

}
