pipeline {

    agent any
    stages {
        /* mvn构建*/
        stage('Build') {
            agent {
               docker {
                  image 'maven:3-alpine'
                   args '-v $HOME/.m2:/root/.m2'
                   reuseNode true
                }
           }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
         /* build镜像并发布到私有仓库中*/
        stage('Push') {
           agent none
    		steps {
    		  script {
                    /*私有仓库登录用户名及密码配置在jenkins用户凭证(Credentials)中，凭证id是dockerHarbor*/
    		        docker.withRegistry('https://yourgithub.com', 'dockerHarbor'){
    				docker.build('yourgithub.com/reponame/config-service:${BUILD_ID}', '-f config-service/src/main/docker/Dockerfile ./config-service').push('latest')
                    docker.build('yourgithub.com/reponame/discovery-service:${BUILD_ID}', '-f discovery-service/src/main/docker/Dockerfile ./discovery-service').push('latest')
                    
    			}
    		  }
    		}
        }
         /* 部署到远程服务器上*/
        stage('Deploy') {
    		steps {
    		  script {
                  /*本机私钥配置在jenkins用户凭证(Credentials)中，凭证id是jenkins-root*/
    		      sshagent(credentials: ['jenkins-root']) {
    		        sh 'ssh -o StrictHostKeyChecking=no -l root 192.168.7.201 -p 2311 docker-compose -f /opt/docker/docker-compose.yml up -d'
                    }
    		  }
    		}
        }
        /* 删除镜像*/
        stage('Rm Images') {
    		steps {
    		  script {
    		      try {
    		          
    		         sh 'docker rmi -f $(docker images | awk "/your-repo/ { print $3}")'
    		      }catch(Exception e) {
                
    		          
    		      }
    		  }
    		}
        }

    }

}
